#imnotevensure
"""classes = []

string = "{\n"

for className in classes.keys():
	string += "\"" + className + "\":{\n"
	string += "},\n\n"

string += "}"""

#typeahead
string = "{\n"
f = [
  "Acio",
  "Auerbach",
  "Bailey",
  "Behling",
  "Bell",
  "Billington",
  "Bourjaily",
  "Brown",
  "Burch",
  "Burden",
  "Zupancic",
  "Burke",
  "Burnett",
  "Campbell",
  "Carey",
  "Chhabra",
  "Cobb",
  "Coffey",
  "Conklin",
  "Culbertson",
  "Cullen",
  "Davis",
  "DelaCuesta",
  "Delfosse",
  "Dell",
  "Ero",
  "Field",
  "Forbes",
  "Foreman",
  "Forgash",
  "Frank",
  "Gabor",
  "Gabriel",
  "Galanos",
  "Gardziel",
  "Gendive",
  "Gilbert",
  "Glotfelty",
  "Glover",
  "Grzelkowski",
  "Hannum",
  "Harris",
  "Hennig",
  "Henry",
  "Holman",
  "Hurowitz",
  "James",
  "Jones",
  "Kauffman",
  "Kemp",
  "Kennedy",
  "Kim",
  "Klein",
  "Kochman",
  "Kosatka",
  "Kosek",
  "Lafever",
  "Laffey",
  "Lampazzi",
  "Larson",
  "Latham",
  "Lewis",
  "Lister",
  "Liu",
  "Locklear",
  "Lowery",
  "Luxenberg",
  "Mateo",
  "McAleer",
  "McConnaughey",
  "McCormick",
  "McNichol",
  "Miller",
  "Monteverde",
  "Moore",
  "Muir",
  "Murphy",
  "Myers",
  "Obeng",
  "Orser",
  "Osborne",
  "Oszko",
  "Otani",
  "Piccione",
  "Pollet",
  "Potoker",
  "Pou",
  "Razzino",
  "Rhee",
  "Romeo",
  "Rose",
  "Rosenblum",
  "Rudwick",
  "Sacks",
  "Sandstrom",
  "Schgallis",
  "Schmitt",
  "Scholla",
  "Scott",
  "Seavey",
  "Sheptyck",
  "Smith",
  "Spoden",
  "Stickler",
  "Struck",
  "Stueben",
  "Taylor",
  "Torbert",
  "Walker",
  "Ware",
  "Waters",
  "Webb",
  "Weber",
  "West",
  "Wickliff",
  "Williams",
  "Wong",
  "Wood",
  "Woodwell",
  "Yi",
  "Young",
  "Zack"
]
for l in f:
	string += "{word: \"%s\" },\n"%l

string += "\n}"
print(string)

"""
#main data
teachers = [
  "Acio",
  "Auerbach",
  "Bailey",
  "Behling",
  "Bell",
  "Billington",
  "Bourjaily",
  "Brown",
  "Burch",
  "Burden",
  "Zupancic",
  "Burke",
  "Burnett",
  "Campbell",
  "Carey",
  "Chhabra",
  "Cobb",
  "Coffey",
  "Conklin",
  "Culbertson",
  "Cullen",
  "Davis",
  "DelaCuesta",
  "Delfosse",
  "Dell",
  "Ero",
  "Field",
  "Forbes",
  "Foreman",
  "Forgash",
  "Frank",
  "Gabor",
  "Gabriel",
  "Galanos",
  "Gardziel",
  "Gendive",
  "Gilbert",
  "Glotfelty",
  "Glover",
  "Grzelkowski",
  "Hannum",
  "Harris",
  "Hennig",
  "Henry",
  "Holman",
  "Hurowitz",
  "James",
  "Jones",
  "Kauffman",
  "Kemp",
  "Kennedy",
  "Kim",
  "Klein",
  "Kochman",
  "Kosatka",
  "Kosek",
  "Lafever",
  "Laffey",
  "Lampazzi",
  "Larson",
  "Latham",
  "Lewis",
  "Lister",
  "Liu",
  "Locklear",
  "Lowery",
  "Luxenberg",
  "Mateo",
  "McAleer",
  "McConnaughey",
  "McCormick",
  "McNichol",
  "Miller",
  "Monteverde",
  "Moore",
  "Muir",
  "Murphy",
  "Myers",
  "Obeng",
  "Orser",
  "Osborne",
  "Oszko",
  "Otani",
  "Piccione",
  "Pollet",
  "Potoker",
  "Pou",
  "Razzino",
  "Rhee",
  "Romeo",
  "Rose",
  "Rosenblum",
  "Rudwick",
  "Sacks",
  "Sandstrom",
  "Schgallis",
  "Schmitt",
  "Scholla",
  "Scott",
  "Seavey",
  "Sheptyck",
  "Smith",
  "Spoden",
  "Stickler",
  "Struck",
  "Stueben",
  "Taylor",
  "Torbert",
  "Walker",
  "Ware",
  "Waters",
  "Webb",
  "Weber",
  "West",
  "Wickliff",
  "Williams",
  "Wong",
  "Wood",
  "Woodwell",
  "Yi",
  "Young",
  "Zack"
]

#final
classes = open('classes.txt', 'r').read().splitlines()
string = "{\n"
string += "\t\"data\" : {\n"

for c in classes[:-1]:
    string += "\t\t \"%s\" : {\n"%c.lower()
    for t in teachers[:-1]:
        string += "\t\t\t \"%s\" : {\"hours\":0, \"hoursVariance\":0, \"difficulty\":0, \"difficultyVariance\":0, \"numEntries\":0},\n"%t.lower()
    string +=  "\t\t\t \"%s\" : {\"hours\":0, \"hoursVariance\":0, \"difficulty\":0, \"difficultyVariance\":0, \"numEntries\":0}\n"%teachers[-1].lower()
    string += "\t\t },\n"

string += "\t\t \"%s\" : {\n"%c.lower()
for t in teachers[:-1]:
    string += "\t\t\t \"%s\" : {\"hours\":0, \"hoursVariance\":0, \"difficulty\":0, \"difficultyVariance\":0, \"numEntries\":0},\n"%t.lower()
        
string +=  "\t\t\t \"%s\" : {\"hours\":0, \"hoursVariance\":0, \"difficulty\":0, \"difficultyVariance\":0, \"numEntries\":0}\n"%teachers[-1].lower()    
string += "\t\t }\n"
string += "\t}\n}"
print(string)"""

        
    
    
    